### PR TITLE
Optimize Microtypo to improve memory usage

### PR DESCRIPTION
**Pull request by ashmaroli**
* redefine `array_exclude` into a private constant `QUEUE`.
  * refactor #recursive_parser to iterate through QUEUE instead of popping.
  * set up `settings` only when needed.
  * rename `array_response` into `bucket`.
  * remove unused method parameters from private methods.
  * fix minor bugs in a few regular expressions.

### CODE REVIEW

**Comment by borisschapira** [comment]
Nice improvements, thanks again! I was goin to optimize the tail call but you know Ruby better than I do and I'm gonna document myself reading your code.
I don't know how to thank you, so I'll just offer you this on-point song: https://youtu.be/-PX0BV9hGZY

I see you're still adding commits, do you want me to merge or wait till you've finished?

**Comment by ashmaroli** [comment]
Thanks for the song, I'm yet to listen to it, though.
But, if you want to test the changes here, do go ahead. I'm done adding commits to this branch :slightly_smiling_face:

**Comment by ashmaroli** [comment]
Thanks for the video, Boris. It was a refreshing break :smiley: :notes:

**Comment by ashmaroli** [comment]
@borisschapira Before you ship this change, I'd recommend adding a complex string to the test-suite just in case I missed something. For example:
```ruby
text = <<~TEXT
  <head>
    <style>...</style>
  </head>
  <body>
    <div>
      <pre>...</pre>
      <code>...</code>
      <!-- nomicrotypo -->...<!-- endnomicrotypo -->
    </div>
    <div>
      <pre>...</pre>
      <code>...</code>
      <!-- nomicrotypo -->...<!-- endnomicrotypo -->
    </div>
    <script>...</script>
  </body>
TEXT
```

**Pull request merged**
